# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'

addons:
  apt:
    packages:
      - cargo # for gifski_renderer

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr);codecov()'
